version: "3.7"
services:
  nginx:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: prod
    ports:
      - "8282:80"
    networks:
      - d8b-network

  ssr:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: ssr
    ports:
      - "8383:4000"
    networks:
      - d8b-network

networks:
  d8b-network:
