name: Testing workflow for pull request
on: [pull_request,workflow_dispatch]
jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [13.x]

        steps:
            - name: Failure step
              run: |
                  doond
                  
            - name: Print context
              #if: ${{ failure() }}
              run: |
                  echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}

            - name: Print test message
              if: ${{ failure() }}
              run: |
                  echo "test1"

            - name: Print test message
              #if: ${{ failure() }}
              run: |
                  echo "test2"
