name: Testing workflow for pull request
on: [pull_request,workflow_dispatch]
jobs:
      build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Failure step
              run: |
                  doond
                  
            - name: Check 1
              if: ${{ failure() }}
              run: |
                  echo "Check 1"

            - name: Check 2
              #if: ${{ failure() }}
              run: |
                  echo "Check 2"

            - name: Check 3
              #if: ${{ failure() }}
              run: |
                  echo "Check 3"

            - name: Check 4
              #if: ${{ failure() }}
              run: |
                  echo "Check 4"
                  
            - name: Check 5
              #if: ${{ failure() }}
              run: |
                  echo "Check 5"

