name: Tests for pull request
on: [pull_request,workflow_dispatch]
jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [13.x]

        steps:
            - name: Print context
              run: |
                  echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
            
            - name: Step that prints name of pull request's author
              run: |
                echo "Pull request's author is: ${REQUEST_AUTHOR}"
              env:
                REQUEST_AUTHOR: ${{ github.actor }}
                                                   # event.head_commit.author.name }}
                
            - name: Step that prints email of pull request's author
              run: |
                echo "Pull request's author is: ${REQUEST_AUTHOR_EMAIL}"
              env:
                REQUEST_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
                
            - name: Step that prints name of pull request's base branch
              run: |
                echo "Pull request's base branch is: ${BASE_BRANCH}"
              env:
                BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
          
            - uses: actions/checkout@v2
              with:
                ref: ${{ github.event.pull_request.head.ref }}

#            - name: Node ${{ matrix.node-version }}
#              uses: actions/setup-node@v1
#              with:
#                  node-version: ${{ matrix.node-version }}

#            - name: Install
#              run: npm install

 #           - name: copy env file
 #             run: |
 #               yes| cp ./src/environments/environment.ts.dist ./src/environments/environment.ts
  
 #           - name: Test
 #             run: npm run test -- --no-watch
