name: Tests for pull request
on: [pull_request,workflow_dispatch]
jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [13.x]

        steps:
            - name: Step that prints name of pull request's base branch
              run: |
                echo "Pull request's base branch is: ${BASE_BRANCH}"
              env:
                BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
          
#            - uses: actions/checkout@v1
#              with:
#                ref: master

#            - name: Node ${{ matrix.node-version }}
#              uses: actions/setup-node@v1
#              with:
#                  node-version: ${{ matrix.node-version }}

#            - name: Install
#              run: npm install

 #           - name: copy env file
 #             run: |
 #               yes| cp ./src/environments/environment.ts.dist ./src/environments/environment.ts
  
 #           - name: Test
 #             run: npm run test -- --no-watch
